# アプリとDBの起動・ネットワークの設定
version: '3.5'

networks:
  default:
    external:
      name: bridge
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.168.1.0/24

services:
  app:
    container_name: go_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      env: dc
    depends_on:
      - godb
    networks:
      app_net:
        ipv4_address: 172.168.1.2
  godb:
    image: mysql:8.0
    container_name: godb
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
#      - ./db/mysql_data:/var/lib/mysql # 永続化している場合、init scriptは実行されない
      - ./db/mysql_conf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: goapi
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "user", "--password=password", "-e", "select 1", "goapi" ]
      interval: 1s
      timeout: 3s
      retries: 20
    networks:
      app_net:
        ipv4_address: 172.168.1.3
