DROP DATABASE IF EXISTS goapi;
CREATE DATABASE IF NOT EXISTS goapi;
USE goapi;

DROP TABLE IF EXISTS WEATHER;
CREATE TABLE IF NOT EXISTS WEATHER
(
dat char(8) NOT NULL,
weather int NOT NULL,
location_id int NOT NULL,
comment varchar(255),
PRIMARY KEY(dat, location_id)
);

DROP TABLE IF EXISTS LOCATION;
CREATE TABLE IF NOT EXISTS LOCATION
(
id int PRIMARY KEY,
city varchar(20) NOT NULL
);

INSERT INTO LOCATION VALUES
(1, "新宿");
