apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minikube
commonLabels:
  seg: local
  cls: minikube
  env: dev
resources:
  - ../../base
patchesJson6902:
  - target:
      kind: Ingress
      name: go-api-ingress
      version: v1beta1
      group: networking.k8s.io
    path: ./ingress.patch.yaml
