logging:
  level: DEBUG
server:
  addr: ":8080"
db:
  driverName: "mysql"
  user: "user"
  password: "password"
  dbname: "goapi"
  addr: "tcp(godb:3306)" #docker-compose
  connmaxlifetime: 3s
  connmaxidletime: 3s
  maxopenconns: 10
  maxidleconns: 10
exapi:
  url: https://www.metaweather.com/api/location/1118370/ #Tokyo
  timeout: 5s
