logging:
  level: INFO
server:
  addr: ":8080"
db:
  driverName: "mysql"
  user: "user"
  password: "password"
  dbname: "goapi"
  addr: "tcp(prod.jp:3306)"
  connmaxlifetime: 3s
  connmaxidletime: 3s
  maxopenconns: 10
  maxidleconns: 10
exapi:
  url: https://www.metaweather.com/api/location/1118370/
  timeout: 5s
