logging:
  level: INFO
server:
  addr: ":8080"
db:
  driverName: "mysql"
  user: "user"
  password: "password"
  dbname: "goapi"
  addr: "tcp(godb:3306)"
exapi:
  url: https://www.metaweather.com/api/location/44418/
  timeout: 3s
