name: integration-test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o go-api-samp .

      - name: Run
        run: |
          export env="local"
          ./go-api-samp &

      - name: Jobs
        run: jobs

      - name: Integration test
        run: export E2E_ENDPOINT="http://localhost:8080" && go test -v -tags e2e ./e2e/...
