name: integration-test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build

      - name: export
        run: export env="local"

      - name: Run
        run: go run main.go &

      - name: Jobs
        run: jobs

      - name: Integration test
        run: go test -v -tags e2e ./e2e/...
